### ISSUE TITLE
complex UniRef query support regression

### ISSUE THREAD

**Issue by MRMHmdeleeuw** [ebi-uniprot/uniprot-rest-api#275]
Hello, in the **legacy UniRef** search, this returns 9 results:

    uniprot:((ec:1.10.3.15) (taxonomy:bacteria))

even though the advanced query builder reformats this search as 

    uniprot:"((ec:1.10.3.15) (taxonomy:bacteria))"

which returns no results. In the **new UniProt** search, this still generates results as expected

    (ec:1.10.3.15) (taxonomy_name:bacteria)

But the **new UniRef** when using 

    uniprot:((ec:1.10.3.15) (taxonomy_name:bacteria))

reports that the ec search field is not supported. What does work is

    1.10.3.15 (taxonomy_name:bacteria)

But that searches the EC number in "all" (whatever that is) and additional restrictions such as (reviewed:true) cannot be specified with a direct UniRef query. The same happens through the REST interface. Please help.

**Comment by LeonardoGonzales** [comment]
Hello MRMHmdeleeuw,

Unfortunately, we currently do not support external collection queries in our new API. (I will raise this issue in our next team meeting).

But, you can resolve your problem, by adding one extra request to get the list of UniProt accession (format=list) and using it as an input to your UniRef query 
1. https://rest.uniprot.org/uniprotkb/search?compressed=true&format=list&query=%28ec%3A1.10.3.15%29%20AND%20%28taxonomy_id%3A2%29&size=250
This will return
B1VTI5
A0A7K0C9D4
A0A539CUU8
A0A7R8RU82

2. For each id  you could query UniRef
https://rest.uniprot.org/uniref/search?format=fasta&query=uniprot_id%3AB1VTI5&size=250
Or using OR clause (as you prefer)
https://rest.uniprot.org/uniref/search?format=fasta&query=uniprot_id%3AB1VTI5%20OR%20uniprot_id%3AA0A7K0C9D4%20OR%20uniprot_id%3AA0A539CUU8%20OR%20uniprot_id%3AA0A7R8RU82&size=250
 
 In this link you can get more help about our API
- https://www.uniprot.org/help/api_queries 

- https://www.uniprot.org/help/return_fields
 
Sorry for this inconvenience 

Best Regards

Leonardo Gonzales

**Comment by MRMHmdeleeuw** [comment]
Hello Leonardo,

Many thanks for the quick follow-up. This looks like a workable solution for me now. Is there any limitation on the query length, i.e. OR-ing 200 uniprot_id's will work?

Best regards,

Marcel de Leeuw

**Comment by LeonardoGonzales** [comment]
Unfortunately we do not have a POST for it. In this case, it would need to search in batches.

**Comment by MRMHmdeleeuw** [comment]
Apologies for not closing this one out earlier. The Gapseq team has long since implemented a new R script to call the current REST API, which I have reviewed and tested only now.
