### ISSUE TITLE
HTTP Response Code 429 returned with no Retry-After  

### ISSUE THREAD

**Issue by dmx2** [ebi-uniprot/uniprot-rest-api#328]
I pull a lot of proteome data and individual entries from UniProt and have recently been receiving a ton of HTTP 429 responses, but the header does not include a "Retry-After" to know when the server wants me to wait.

**Comment by ahmadshadab** [comment]
Hi @dmx2 ,
Sorry for the delayed response. You are right, we don't have "Retry-After" header. 
Could you email us more details to help@uniprot.org ?
Details like your sample request, query etc
Thanks,
Shadab

**Comment by ahmadshadab** [comment]
Closing it, i will file a Jira ticket for the same.
